var tree = [ { content: 'marked', slug: 'marked', lvl: 1, i: 0, seen: 0 },
  { content: 'Install', slug: 'install', lvl: 2, i: 1, seen: 0 },
  { content: 'Usage', slug: 'usage', lvl: 2, i: 2, seen: 0 },
  { content: 'Browser', slug: 'browser', lvl: 3, i: 3, seen: 0 },
  { content: 'marked(markdownString [,options] [,callback])',
    slug: 'markedmarkdownstring-options-callback',
    lvl: 2,
    i: 4,
    seen: 0 },
  { content: 'markdownString',
    slug: 'markdownstring',
    lvl: 3,
    i: 5,
    seen: 0 },
  { content: 'options', slug: 'options', lvl: 3, i: 6, seen: 0 },
  { content: 'callback', slug: 'callback', lvl: 3, i: 7, seen: 0 },
  { content: 'Options', slug: 'options', lvl: 2, i: 8, seen: 0 },
  { content: 'highlight', slug: 'highlight', lvl: 3, i: 9, seen: 0 },
  { content: 'highlight arguments',
    slug: 'highlight-arguments',
    lvl: 4,
    i: 10,
    seen: 0 },
  { content: 'renderer', slug: 'renderer', lvl: 3, i: 11, seen: 0 },
  { content: 'Overriding renderer methods',
    slug: 'overriding-renderer-methods',
    lvl: 4,
    i: 12,
    seen: 0 },
  { content: 'Block level renderer methods',
    slug: 'block-level-renderer-methods',
    lvl: 4,
    i: 13,
    seen: 0 },
  { content: 'Inline level renderer methods',
    slug: 'inline-level-renderer-methods',
    lvl: 4,
    i: 14,
    seen: 0 },
  { content: 'gfm', slug: 'gfm', lvl: 3, i: 15, seen: 0 },
  { content: 'tables', slug: 'tables', lvl: 3, i: 16, seen: 0 },
  { content: 'breaks', slug: 'breaks', lvl: 3, i: 17, seen: 0 },
  { content: 'pedantic', slug: 'pedantic', lvl: 3, i: 18, seen: 0 },
  { content: 'sanitize', slug: 'sanitize', lvl: 3, i: 19, seen: 0 },
  { content: 'smartLists',
    slug: 'smartlists',
    lvl: 3,
    i: 20,
    seen: 0 },
  { content: 'smartypants',
    slug: 'smartypants',
    lvl: 3,
    i: 21,
    seen: 0 },
  { content: 'Access to lexer and parser',
    slug: 'access-to-lexer-and-parser',
    lvl: 2,
    i: 22,
    seen: 0 },
  { content: 'CLI', slug: 'cli', lvl: 2, i: 23, seen: 0 },
  { content: 'Philosophy behind marked',
    slug: 'philosophy-behind-marked',
    lvl: 2,
    i: 24,
    seen: 0 },
  { content: 'Benchmarks',
    slug: 'benchmarks',
    lvl: 2,
    i: 25,
    seen: 0 },
  { content: 'Pro level', slug: 'pro-level', lvl: 3, i: 26, seen: 0 },
  { content: 'Running Tests & Contributing',
    slug: 'running-tests--contributing',
    lvl: 2,
    i: 27,
    seen: 0 },
  { content: 'Contribution and License Agreement',
    slug: 'contribution-and-license-agreement',
    lvl: 3,
    i: 28,
    seen: 0 },
  { content: 'License', slug: 'license', lvl: 2, i: 29, seen: 0 } ]